### PR TITLE
chore: add lnav definitions and install

### PR DESCRIPTION
**Pull request by lamchau**
I found [`lnav`](https://lnav.org/) useful during development on `ftl` so I put together a quick definition for others that might find value with it (i.e. when there are multiple verbs in play).

image

### CODE REVIEW

**Comment by alecthomas** [comment]
It looks like there are statically linked binaries - can you make a Hermit package for it please?

**Comment by alecthomas** [comment]
Interesting, but what are you thinking we'd use this for in FTL? I don't think I ever merge multiple logs during day-to-day development.

**Comment by lamchau** [comment]
> It looks like there are statically linked binaries - can you make a Hermit package for it please?

sure! i can make it a hermit package but do we want to add it as a dependency? i was thinking of keeping it optional since it's personal preference.

> Interesting, but what are you thinking we'd use this for in FTL? I don't think I ever merge multiple logs during day-to-day development.

for me most of the time it's in the background for me to see colorized/formatted/filtered logs. since i get lost in monochromatic logs. but to your point, definitely the collation of logs isn't standard, just a bonus feature!

**Comment by alecthomas** [comment]
Okay, well while it sounds useful, I think we want to keep tools/scripts in the FTL repo specific to FTL itself. Thanks for the thought though!

**Comment by lamchau** [comment]
for posterity: moved to here https://gist.github.com/lamchau/e6e61c7dec8d6400a4fac42f9726cb11

**Pull request closed without merging**
