### PR TITLE
chore: add integration test for omitempty encoding at ingress

### PR DESCRIPTION
**Pull request by deniseli**
Addresses https://github.com/TBD54566975/ftl/pull/1441#discussion_r1594443695

Tested with `go test --tags=integration ./integration/... -run TestHTTPEncodeOmitempty`

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]
Nice!

**Comment by alecthomas** [comment]
Does `omitempty` work for optional types?

**Comment by deniseli** [comment]
> Does `omitempty` work for optional types?

Yes! Thought it encodes to `null` rather than `""` for an `ftl.None[string]()`. I realized I missed that branch case in the unit tests so I added that in too :)

**Comment by alecthomas** [comment]
`omitempty` in conjunction with `Option` should result in the field being omitted entirely - you should be able to use `reflect.Value.IsZero()` to check that case

**Comment by wesbillman** [comment]
Nice one @deniseli!!

**Comment by deniseli** [comment]
Ah, sorry, I misspoke entirely last time. The field that is tagged `omitempty` is indeed omitted completely. The `null` is just for the cases where it the field is an `ftl.Option` but _not_ tagged `omitempty`. So looks like we're good, I'll go ahead and merge. Sorry for the confusion!

**Comment by alecthomas** [comment]
Oh nice, perfect!

**Pull request merged**
