### PR TITLE
fix(topic): require lowerCamel topic names instead of lower_snake

### LINKED ISSUE #2328: Migrate naming of topics/subscriptions to lowerCamelCase
They are currently lower_snake_case, which is inconsistent with all other identifiers in FTL. This will entail something like:

1. Change FTL to require lowerCamelCase.
2. Change source code from eg. `var OutgoingMessagesTopic = ftl.Topic[OutgoingMessageEvent]("outgoing_messages_topic")` to `var OutgoingMessagesTopic = ftl.Topic[OutgoingMessageEvent]("outgoingMessagesTopic")`
3. Rename topics in database.

### PR DESCRIPTION
**Pull request by safeer**
Breaking change, fixes #2328

Original topic name PR is #1958

### CODE REVIEW

**Review by deniseli — APPROVED** [review]
Do we need to hold off on merging this? It's any easy-enough change on the customer repo, but if they need to do some sort of emergency deploy, it'd be annoying if they suddenly needed to rename all the topics at the same time.

**Comment by wesbillman** [comment]
Maybe we can just plan this with the customer repo. It might be a good time to get some of this in and we can manually update the db(s) as needed to get them running again. I'm happy to help with this and pair with us/them on getting it deployed.

**Comment by alecthomas** [comment]
@mistermoe has said it's okay to wipe the databases (except the secrets) table

@gak also has a breaking change he wants to get in, so let's merge these changes but not deploy until we have both in

**Comment by wesbillman** [comment]
> @mistermoe has said it's okay to wipe the databases (except the secrets) table
> 
> @gak also has a breaking change he wants to get in, so let's merge these changes but not deploy until we have both in

@alecthomas I was going to help deploy the topic names PR today, but sounds like we'll need to wait for @gak's change as well, so we can do a deploy this evening or tomorrow instead 👍

**Pull request merged**
