### PR TITLE
feat: log name of the calling verb to PublishEvent in otel metric attributes

### PR DESCRIPTION
**Pull request by deniseli**
Add `ftl.pubsub.publish.caller.verb.name` attribute to `ftl.pubsub.published` metric. Only the verb name, not module, is needed because the module will be the same as the topic's module, which is already logged (`ftl.module.name`)

Please let me know if there are DB changes I missed that should be included in this PR :)

```
Metric #0
Descriptor:
     -> Name: ftl.pubsub.published
     -> Description: the number of times that an event is published to a topic
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative

NumberDataPoints #0
Data point attributes:
     -> ftl.module.name: Str(echo)
     -> ftl.pubsub.publish.caller.verb.name: Str(Echo)
     -> ftl.pubsub.topic.name: Str(echotopic)
     -> ftl.status.succeeded: Bool(true)
StartTimestamp: 2024-07-31 17:28:47.451585 +0000 UTC
Timestamp: 2024-07-31 17:29:12.44603 +0000 UTC
Value: 1
```

Issue: https://github.com/TBD54566975/ftl/issues/2194

### CODE REVIEW

**Review by jonathanj-square — APPROVED** [review]
If the calling verb is, by design, only allowed to come from the same module then this lgtm. 

When we add support for multiple modules running in a cluster I wonder if that relationship will hold

**Comment by deniseli** [comment]
> If the calling verb is, by design, only allowed to come from the same module then this lgtm.
> 
> When we add support for multiple modules running in a cluster I wonder if that relationship will hold

Yup indeed, they are currently required to come from the same module: https://github.com/TBD54566975/ftl/blob/fbd2d1a48fa8c398cdb82392dace05c2237f3b2f/go-runtime/internal/impl.go#L73

**Comment by deniseli** [comment]
This PR doesn't persist the caller, so if we want to retrieve that later, we'll need to add `caller` to the `topic_events` table

**Comment by deniseli** [comment]
> This PR doesn't persist the caller, so if we want to retrieve that later, we'll need to add `caller` to the `topic_events` table. That would let us record the `caller` attribute on all the other pubsub metrics too, which would be awesome. I'll add a todo for myself

https://github.com/TBD54566975/ftl/pull/2231

**Pull request merged**
