### PR TITLE
test: improve watch test reliability

### LINKED ISSUE #1419: CI failing watch tests sometimes
Flaky...

```
=== Failed
=== FAIL: buildengine TestWatch (10.38s)
debug: added module "one"
debug: removed module "one"
debug: added module "one"
    /home/runner/work/ftl/ftl/buildengine/watch_test.go:56: expected at least 4 events, got 3

=== FAIL: buildengine TestWatchWithBuildModifyingFiles (unknown)
debug: removed module "one"
panic: send on closed channel

goroutine 13911 [running]:
github.com/alecthomas/types/pubsub.(*Topic[...]).Publish(...)
	/home/runner/go/pkg/mod/github.com/alecthomas/types@v0.14.0/pubsub/pubsub.go:78
github.com/TBD[54](https://github.com/TBD54566975/ftl/actions/runs/8977809220/job/24657203701?pr=1418#step:6:55)566975/ftl/buildengine.(*Watcher).Watch.func1()
	/home/runner/work/ftl/ftl/buildengine/watch.go:108 +0x7b4
created by github.com/TBD54[56](https://github.com/TBD54566975/ftl/actions/runs/8977809220/job/24657203701?pr=1418#step:6:57)6975/ftl/buildengine.(*Watcher).Watch in goroutine 13909
	/home/runner/work/ftl/ftl/buildengine/watch.go:78 +0x2b1

DONE 308 tests, 1 skipped, 2 failures in 95.391s
Error: === RUN   TestWatch
debug: added module "one"
debug: removed module "one"
debug: added module "one"
    buildengine/watch_test.go:56: expected at least 4 events, got 3
--- FAIL: TestWatch (10.38s)

::error file=	/home/runner/work/ftl/ftl/buildengine/watch.go
	/home/runner/work/ftl/ftl/buildengine/watch.go,line=108 +0x7b4
78 +0x2b1::=== RUN   TestWatchWithBuildModifyingFiles%0Adebug: removed module "one"%0Apanic: send on closed channel%0A%0Agoroutine 13911 [running]:%0Agithub.com/alecthomas/types/pubsub.(*Topic[...]).Publish(...)%0A	/home/runner/go/pkg/mod/github.com/alecthomas/types@v0.14.0/pubsub/pubsub.go:78%0Agithub.com/TBD545[66](https://github.com/TBD54566975/ftl/actions/runs/8977809220/job/24657203701?pr=1418#step:6:67)975/ftl/buildengine.(*Watcher).Watch.func1()%0A	buildengine/watch.go:108 +0x7b4%0Acreated by github.com/TBD5456[69](https://github.com/TBD54566975/ftl/actions/runs/8977809220/job/24657203701?pr=1418#step:6:70)75/ftl/buildengine.(*Watcher).Watch in goroutine 13909%0A	buildengine/watch.go:78 +0x2b1%0A
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by matt2e**
fixes #1419

Instead of calling `sleep` and trying to synchronise with the watcher's timing, this changes the logic to listen for expected events before continuing.

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]
Nice!

**Comment by matt2e** [comment]
Looking into why the test is failing with a new error:
```
Error: === RUN   TestWatch
debug: added module "one"
debug: removed module "one"
    buildengine/watch_test.go:43: unexpected event removed:one instead of [added:one added:two]
--- FAIL: TestWatch (9.91s)
```

**Comment by matt2e** [comment]
Second fix:
- `ftl init ...` scaffolds a `go.mod` file with the ftl version set to `latest`
- `discoverModules` finds the module, looks in the `go.mod` file for replacements (newish behavior) to follow but errors when it can't parse the file with `latest` (expects `v_._._`)
- watcher ignores this error and believes the new module list (empty)
- watcher sends events saying all known modules have been removed

I added this behavior to ignore the error when discovering modules & external libraries in watcher... But I don't remember why. Looks like a mistake now.

**Comment by matt2e** [comment]
Mm they are a bit unrelated, its no longer just a test fix. Will move the second fix into a separate PR

**Pull request merged**
