### PR TITLE
fix: maybe fix rare npe

### LINKED ISSUE #2251: Rare flaky nil pointer during test
```
info:customers: Building module
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1005bd2ac]

goroutine 101 [running]:
github.com/TBD54566975/ftl/go-runtime/schema.analyzersWithDependencies(...)
        github.com/TBD54566975/ftl/go-runtime/schema/extract.go:291
github.com/TBD54566975/ftl/go-runtime/schema.Extract({0x14000881e40?, 0x1014eb9f3?})
        github.com/TBD54566975/ftl/go-runtime/schema/extract.go:108 +0x360
github.com/TBD54566975/ftl/go-runtime/compile.Build({0x101fa46d8, 0x140008020f0}, {0x1400044b9e0, 0x1e}, {0x14000881e40, 0x34}, 0x140002f5b00, {0x103371398, 0x14000338920})
        github.com/TBD54566975/ftl/go-runtime/compile/build.go:157 +0x878
github.com/TBD54566975/ftl/buildengine.buildGoModule({0x101fa46d8?, 0x140008020f0?}, {0x1400044b9e0?, 0x1e?}, _, {{{0x14000881e40, 0x34}, {0x140000ba8b0, 0x2}, {0x140000ba8b4, ...}, ...}, ...}, ...)
        github.com/TBD54566975/ftl/buildengine/build_go.go:13 +0x70
github.com/TBD54566975/ftl/buildengine.buildModule({0x101fa46d8, 0x14000670f60}, {0x1400044b9e0, 0x1e}, _, {{{0x14000881e40, 0x34}, {0x140000ba8b0, 0x2}, {0x140000ba8b4, ...}, ...}, ...}, ...)
        github.com/TBD54566975/ftl/buildengine/build.go:50 +0x57c
github.com/TBD54566975/ftl/buildengine.Build({0x101fa46d8?, 0x14000670f60?}, {0x1400044b9e0?, 0x0?}, _, {{{0x14000881e40, 0x34}, {0x140000ba8b0, 0x2}, {0x140000ba8b4, ...}, ...}, ...}, ...)
        github.com/TBD54566975/ftl/buildengine/build.go:27 +0x54
github.com/TBD54566975/ftl/buildengine.(*Engine).build(0x14000886e00, {0x101fa46d8, 0x14000670f60}, {0x140000bbf35, 0x5}, 0x1400032e900, 0x140000af380)
        github.com/TBD54566975/ftl/buildengine/engine.go:703 +0x350
github.com/TBD54566975/ftl/buildengine.(*Engine).tryBuild(0x14000886e00, {0x101fa46d8, 0x14000670f60}, 0x1400027a390, {0x140000bbf35, 0x5}, 0x1400032e900, 0x140000af380, 0x0)
        github.com/TBD54566975/ftl/buildengine/engine.go:671 +0x2b8
github.com/TBD54566975/ftl/buildengine.(*Engine).buildWithCallback.func2()
        github.com/TBD54566975/ftl/buildengine/engine.go:606 +0x3a0
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98
error: Recipe `build` failed with exit code 2
error: Recipe `test` failed with exit code 2
```

### PR DESCRIPTION
**Pull request by worstell**
still haven't been able to repro but attempts to fix #2251

### CODE REVIEW

**Review by wesbillman — APPROVED** [review]
Looks like it should cover that panic!

**Comment by stuartwdouglas** [comment]
Why doesn't it panic all the time though? Doesn't this code get run with the exact inputs every time?

Also code like the following does not result in a panic:

```
	var foo []*analysis.Analyzer
	var bar []*analysis.Analyzer
	foo = append(foo, bar...)
	println(foo)
```

I think the only way we could get this error is if one of the extractors is null somehow.

**Comment by worstell** [comment]
> Why doesn't it panic all the time though? Doesn't this code get run with the exact inputs every time?
> 
> Also code like the following does not result in a panic:
> 
> ```
> 	var foo []*analysis.Analyzer
> 	var bar []*analysis.Analyzer
> 	foo = append(foo, bar...)
> 	println(foo)
> ```
> 
> I think the only way we could get this error is if one of the extractors is null somehow.

yeah i'm not sure why the failure is occurring. it appears to be flaky and infrequent, and i haven't been able to repro it at all myself. this just kind of blindly attempts to add some safeguards based on the stack trace, but it's still a bit of a mystery to me

will add another check to only add non-null extractors from `Extractor[i]` just in case that's the issue

**Comment by stuartwdouglas** [comment]
But if the extractor is null won't that mean that extraction will potentially not work 100%, resulting in even harder to diagnose flakiness?

**Comment by stuartwdouglas** [comment]
Is it possible that this is a variable init order issue? From the golang spec:

```

Dependency analysis is performed per package; only references referring to variables, functions, and (non-interface) methods declared in the current package are considered. If other, hidden, data dependencies exists between variables, the initialization order between those variables is unspecified.
```

Does this mean that the array could be created at a time when some of the variables it refers to are not initialized yet as they are in different packages? I am not a go expert so this may be a question for @alecthomas

**Comment by alecthomas** [comment]
I haven't looked in detail at the code to see if this is what is happening, but yes, if there are values initialised when the runtime starts, inter-package ordering is not guaranteed.

**Comment by worstell** [comment]
> I haven't looked in detail at the code to see if this is what is happening, but yes, if there are values initialised when the runtime starts, inter-package ordering is not guaranteed.

is wrapping the assignment of the `Extractors` var in an `init()` block the correct solution for that?

**Pull request merged**
