### PR TITLE
fix: add commands section to ftl-project

### LINKED ISSUE #1179: Need a way to replace `just dev` to run other commands before `ftl dev .`
Currently, is some of the customer's repo we use `just` run commands before `ftl dev .`.

For example that just command might look something like this `just dev`:
```sh
# Start the FTL backend in "dev mode".
dev:
  # Restart when any migrations change.
  watchexec -r -f '**/migrations/*.sql' 'just db-migrate-all && ftl dev backend/modules --recreate'
```

This will run db migrations before starting ftl dev and rerun both if anything changes.

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1179 1179

### CODE REVIEW

**Comment by matt2e** [comment]
The name "pre-build" led me astray a bit. I thought it might be run pre-building any module, rather than just at the start.

**Comment by wesbillman** [comment]
Gotcha. Maybe `before-build`? Open to suggestions :)

**Comment by matt2e** [comment]
`init-commands`? `before-build` still sounds like it runs before building a module to me

**Comment by matt2e** [comment]
nah i like this :)

**Pull request merged**
