### PR TITLE
chore: remove type-specific Ref variants from schema

### LINKED ISSUE #1043: consolidate all typed refs into single generic ref
refactor !!!!!

### LINKED ISSUE #1063: Eradicate type-specific "Ref" variants in schema
They're proliferating at a rate of knots and are increasing the noise and complexity of the schema. Instead, switch to using the single untyped `Ref`, and a single resolver function that returns different types.

### PR DESCRIPTION
**Pull request by worstell**
fixes #1043
fixes #1063

### CODE REVIEW

**Comment by alecthomas** [comment]
@worstell  CI has failed, but it doesn't report it because of the autofmt...very irritating

**Comment by alecthomas** [comment]
If you run `autofmt` locally it will fix this up.

**Comment by alecthomas** [comment]
Filed #1075

**Review by alecthomas — APPROVED** [review]
Feels good man

**Comment by worstell** [comment]
> If you run `autofmt` locally before you push it will fix this up.

the more you know!!!

**Pull request merged**
