### PR TITLE
feat: maintain idle pool of runners

### LINKED ISSUE #1030: Implement reserved free runner pool
Currently in development we're suppressing this error:

```
warn:controller0: Failed to increase deployment replicas: failed to claim runners for oidcauth-86ae51d623: no idle runners found matching labels {"languages":["go"]}: not found
```

Because it triggers every time a new deployment is created. This message should not be suppressed however, and should probably be logged at error level.

A solution to this is to implement the reserved free runner pool that was in the original design for the autoscaling. That is, the controller will guarantee that a minimum number of free runners are always available.

### LINKED ISSUE #1036: Runner id collisions causes runner kill loop with LocalScaling deterministic runner IDs
Steps to repro
- `ftl serve --recreate --log-level=DEBUG`
- `ftl deploy examples/go`
- `ftl ps --verbose`
- `ftl kill ___` <-- choose the deployment with a lower runner id, which is the `time` one
- At this point there will be a remaining runner with an id like `R00000000000000000000004000`
- `ftl deploy examples/go/time`
- LocalScaling then creates a new runner, but chooses the id to be `R00000000000000000000004000` (it's generated using the current number of runners)
- The leads to the existing runner with that id to be killed to allow this one to start up. Which then causes another runner to be kicked off to redeploy the `echo` deployment, and the cycle starts to repeat

### PR DESCRIPTION
**Pull request by matt2e**
Adds `--idle-runners` arg to define how large the idle pool should be.

Fixes #1036
Fixes #1030

### Previous notes
Currently a draft because this PR makes #1036 more likely to be hit.
Before this change, killing all deployments would mean there are 0 runners, leading to no runner id collisions when you bring up more deployments
After this change, killing all deployments means that there will still be runners which will cause collisions if the idle runner ids aren't the lowest possible [`R00000000000000000000002000`, `R00000000000000000000004000` ... ]

I've been testing with a hacky fix replacing line `bankend/controller/scaling/local_scaling.go:96` to:
```
binary.BigEndian.PutUint32(ulid[10:], rand.Uint32())
```

### CODE REVIEW

**Comment by matt2e** [comment]
Is 1 a good default idle pool size?

**Comment by alecthomas** [comment]
I think it would be best fix #1036 in this PR.

**Comment by matt2e** [comment]
> I think it would be best fix #1036 in this PR.

Will give it a go

**Comment by alecthomas** [comment]
It might be best just randomly generate them like it does in production.

**Comment by matt2e** [comment]
Ah, just did a an ever increasing version. Happy to switch it over to what we do in prod though if you prefer. Have the simpler ids been helpful in development up to now? Otherwise keeping it closer to prod seems like a better choice

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
> Ah, just did a an ever increasing version. Happy to switch it over to what we do in prod though if you prefer. Have the simpler ids been helpful in development up to now? Otherwise keeping it closer to prod seems like a better choice

I think the idea was that it would make it slightly easier to debug, but I don't recall in practice ever relying on it or even caring.

**Pull request merged**
