### PR TITLE
chore: simplify Dockerfiles

### PR DESCRIPTION
**Pull request by alecthomas**
Consolidates on a single `Dockerfile` for all primary services. Language-specific runners require a separate Dockerfile each in the form `Dockerfile.runner-<language>`. Build all of these with `just build-docker <name>`, eg. `just build-docker runner-jvm`.

Also adds a `just list-docker-images`, and updates ci.yml to build via a matrix using this.

> [!WARNING]
> In order to simplify the Dockerfiles this changes a bunch of environment variables , which might break due to downstream infra that set the old values.

### CODE REVIEW

**Review by stuartwdouglas — DISMISSED** [review]
I think we also need to update the release workflows.

**Review by stuartwdouglas — COMMENTED** [review]
Also the Justfile in ./deployments needs to be updated, as it was relying on the `.test` dockerfiles.

**Comment by alecthomas** [comment]
> I think we also need to update the release workflows.

Already done :)

**Comment by alecthomas** [comment]
> Also the Justfile in ./deployments needs to be updated, as it was relying on the `.test` dockerfiles.

Updated, but I'm not sure it's being exercised in CI (?), so it might need a manual check potentially.

**Comment by alecthomas** [comment]
> > Also the Justfile in ./deployments needs to be updated, as it was relying on the `.test` dockerfiles.
> 
> Updated, but I'm not sure it's being exercised in CI (?), so it might need a manual check potentially.

Mmm well some of the CI jobs are failing, so I guess that answers that question 😂

**Comment by alecthomas** [comment]
> Smoke Test Upgrade Path got broken by a different PR, so don't worry about that one. I can look at fixing TestKubeScaling tomorrow if you want.

Ah, kk. I _think_ I have TestKubeScaling working, it was just some stupid stuff in the builds.

**Comment by alecthomas** [comment]
Mmm okay I spoke too soon; everything is working except TestKubeScaling :(

**Pull request merged**
